# Generated by Django 5.2.5 on 2025-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('payer', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DENIED', 'Denied'), ('PENDING', 'Pending'), ('APPEALED', 'Appealed'), ('PAID', 'Paid')], default='DENIED', max_length=30)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
