# Generated by Django 5.2.5 on 2025-08-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
