# Generated by Django 5.2.5 on 2025-08-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_paid_amount_alter_claim_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_codes', models.TextField(blank=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='claims.claim')),
            ],
        ),
    ]
