# Generated by Django 5.2.5 on 2025-09-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_flagged_claimnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimnote',
            name='body',
            field=models.TextField(),
        ),
    ]
