# Generated by Django 5.2.5 on 2025-09-08 01:59

from django.db import migrations, models
from datetime import date

def backfill_service_date(apps, schema_editor):
    Claim = apps.get_model('claims', 'Claim')
    # Ensure any NULLs are filled before we make the column non-null.
    Claim.objects.filter(service_date__isnull=True).update(service_date=date(2000, 1, 1))


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimnote_body'),
    ]

    operations = [
        # If your 0006 originally had AddIndex operations, keep them too
        migrations.RunPython(backfill_service_date, migrations.RunPython.noop),

        # Now alter the field WITHOUT a default
        migrations.AlterField(
            model_name="claim",
            name="service_date",
            field=models.DateField(db_index=True),
        ),

    # operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='claim',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='patient_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='claim',
            name='payer',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_date',
            field=models.DateField(db_index=True, default=-2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'last_updated'], name='claim_status_lastupd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['flagged', 'last_updated'], name='claim_flag_lastupd_idx'),
        ),
    ]
